// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang -std=c++11 -S -O2 -msse4.2 -o - %s | FileCheck -check-prefix=CHECK-SSE42 %s
// RUN: %clang -std=c++11 -S -O2 -mavx2 -o - %s | FileCheck -check-prefix=CHECK-AVX2 %s
#include "dimsum.h"
using namespace dimsum;

extern "C" {

// CHECK-SSE42-LABEL: test_static_simd_cast_0:
// CHECK-SSE42:       # %bb.0: # %entry
// CHECK-SSE42-NEXT:    cvtdq2ps %xmm0, %xmm0
// CHECK-SSE42-NEXT:    retq
//
// CHECK-AVX2-LABEL: test_static_simd_cast_0:
// CHECK-AVX2:       # %bb.0: # %entry
// CHECK-AVX2-NEXT:    vcvtdq2ps %xmm0, %xmm0
// CHECK-AVX2-NEXT:    retq
Simd128<float> test_static_simd_cast_0(Simd128<int32> a) {
  return static_simd_cast<float>(a);
}

// CHECK-SSE42-LABEL: test_static_simd_cast_1:
// CHECK-SSE42:       # %bb.0: # %entry
// CHECK-SSE42-NEXT:    cvttps2dq %xmm0, %xmm0
// CHECK-SSE42-NEXT:    retq
//
// CHECK-AVX2-LABEL: test_static_simd_cast_1:
// CHECK-AVX2:       # %bb.0: # %entry
// CHECK-AVX2-NEXT:    vcvttps2dq %xmm0, %xmm0
// CHECK-AVX2-NEXT:    retq
Simd128<int32> test_static_simd_cast_1(Simd128<float> a) {
  return static_simd_cast<int32>(a);
}

}
