// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang -std=c++11 -S -O2 -mavx2 -o - %s | FileCheck -check-prefix=CHECK-AVX2 %s
#include "dimsum.h"
using namespace dimsum;

extern "C" {

// CHECK-AVX2-LABEL: test_static_simd_cast_0:
// CHECK-AVX2:       # %bb.0: # %entry
// CHECK-AVX2-NEXT:    vcvtdq2ps %ymm0, %ymm0
// CHECK-AVX2-NEXT:    retq
NativeSimd<float> test_static_simd_cast_0(NativeSimd<int32> a) {
  return static_simd_cast<float>(a);
}

// CHECK-AVX2-LABEL: test_static_simd_cast_1:
// CHECK-AVX2:       # %bb.0: # %entry
// CHECK-AVX2-NEXT:    vcvttps2dq %ymm0, %ymm0
// CHECK-AVX2-NEXT:    retq
NativeSimd<int32> test_static_simd_cast_1(NativeSimd<float> a) {
  return static_simd_cast<int32>(a);
}

}
